Deleted qnx4 directories and *.tmpl files; renamed "cvsignore" into .gitignore; started changing mkkercalls
Signed-off-by: Yuri Zaporozhets <r_tty@yahoo.co.uk>

diff --git a/userland/lib/c/kercalls/mkkercalls b/userland/lib/c/kercalls/mkkercalls
--- a/userland/lib/c/kercalls/mkkercalls
+++ b/userland/lib/c/kercalls/mkkercalls
@@ -1,14 +1,6 @@
-#!/usr/bin/env ksh
+#! /bin/bash
 
 rootdir=${0%/*}
-if [ "${rootdir}" = "${0}" ]; then
-	# In place for Windows.  Any normal shell expansion of \ characters
-      # should be stripped away by this point.  This is needed to build from cmd.exe
-	rootdir=${0%\\*}
-	if [ "${rootdir}" = "${0}" ]; then
-		rootdir=.
-	fi
-fi
 
 extension=s
 kcprefix=""
@@ -51,7 +43,9 @@ if [ "${test_mode}" ]; then
 fi
 
 if [ $# -lt 2 ]; then
-	echo Expecting at least 2 arguments >&2
+	echo "Expecting at least 2 arguments:"  >&2
+	echo "  1st arg: path/to/kercalls.h"    >&2
+	echo "  2nd arg: path/to/arch/template" >&2
 	exit 1
 fi
 
@@ -61,23 +55,24 @@ else
 	outdir=$3
 fi
 
-if [ ! -r "${rootdir}/$2/template" ]; then
-	echo "Missing '$2' template file" >&2
+if [ ! -r $2 ]; then
+	echo "Missing template file $2" >&2
 	exit 1
 fi
 
-. ${rootdir}/$2/template
+. $2
 
 # parse the <sys/kercalls.h> file to find the kercall names & numbers
 function parse_header {
 	let "kcnum = 0"
+	
 	while read -r name remainder; do
 		root=${name#__KER_}
 		if [ "${root}" != "${name}" ]; then
 			root=${root%,}
 			eval kc_${root}=${kcnum}
 			let "kcnum = ${kcnum} + 1"
-		fi	
+		fi
 	done
 }
 
@@ -96,9 +91,9 @@ function generate {
 				exit 1
 			fi
 			fullname=${kcprefix}${name}
-			gen_call ${fullname} ${kcnum} ${nparms} NONE "${neglist}" >${outdir}/${name}.${extension}
+			gen_call ${fullname} ${kcnum} ${nparms} NONE "${neglist}"
 			if [ "${rent}" != "NONE" ]; then
-				gen_call "${fullname}_r" ${kcnum} ${nparms} ${rent} "${neglist}" >${outdir}/${name}_r.${extension}
+				gen_call "${fullname}_r" ${kcnum} ${nparms} ${rent} "${neglist}"
 			fi
 			;;
 		esac
@@ -106,47 +101,48 @@ function generate {
 }
 
 parse_header <$1
-
-generate <<HERE
+	echo -e "/*\n * System call definition file for $ARCH\n */\n\n#include \"asmoff.def\""
+syscall_file_hdr
+generate << HERE
 
 # name				kercall_number	   #parms	rent	neg_list
 
-__Ring0  			RING0					1	NORMAL
-__traceevent  		TRACE_EVENT 			1	NONE
-__interruptmask  	INTERRUPT_MASK 			1	NONE
-__interruptunmask  	INTERRUPT_UNMASK 		1	NONE
-__kerbad  			BAD 					0	NONE
-__kernop  			NOP 					0	NONE
+__Ring0  		RING0				1	NORMAL
+__traceevent		TRACE_EVENT 			1	NONE
+__interruptmask		INTERRUPT_MASK 			1	NONE
+__interruptunmask	INTERRUPT_UNMASK 		1	NONE
+__kerbad		BAD 				0	NONE
+__kernop		NOP 				0	NONE
 __SysCpupageGet 	SYS_CPUPAGE_GET 		1	NONE
 __SysCpupageSet 	SYS_CPUPAGE_SET 		2	NONE
-NetCred 			NET_CRED 				2	NONE
+NetCred 		NET_CRED 			2	NONE
 NetInfoscoid 		NET_INFOSCOID 			2	NONE
-NetUnblock 			NET_UNBLOCK 			1	NONE
-NetVtid 			NET_VTID 				2	NONE
+NetUnblock 		NET_UNBLOCK 			1	NONE
+NetVtid 		NET_VTID 			2	NONE
 NetSignalKill  		NET_SIGNAL_KILL  		2	NONE
 ChannelCreate  		CHANNEL_CREATE  		1	NEGATIVE
 ChannelCreateExt 	CHANNEL_CREATE  		6	NONE
 ChannelDestroy  	CHANNEL_DESTROY  		1	NORMAL
 ChannelConnectAttr 	CHANCON_ATTR  			4	NONE
-ClockAdjust  		CLOCK_ADJUST  			3	NORMAL
-ClockPeriod  		CLOCK_PERIOD  			3	NORMAL
-ClockTime  			CLOCK_TIME  			3	NORMAL
-ClockId  			CLOCK_ID  				2	NEGATIVE
-ConnectAttach 		CONNECT_ATTACH  		5	NEGATIVE
-ConnectAttachExt 	CONNECT_ATTACH  		6	NONE
-ConnectClientInfo  	CONNECT_CLIENT_INFO  	3	NORMAL
+ClockAdjust		CLOCK_ADJUST  			3	NORMAL
+ClockPeriod		CLOCK_PERIOD  			3	NORMAL
+ClockTime		CLOCK_TIME  			3	NORMAL
+ClockId			CLOCK_ID  			2	NEGATIVE
+ConnectAttach		CONNECT_ATTACH  		5	NEGATIVE
+ConnectAttachExt	CONNECT_ATTACH  		6	NONE
+ConnectClientInfo	CONNECT_CLIENT_INFO		3	NORMAL
 ConnectDetach  		CONNECT_DETACH  		1	NORMAL
 ConnectFlags  		CONNECT_FLAGS  			4	NEGATIVE
-ConnectServerInfo  	CONNECT_SERVER_INFO  	3	NEGATIVE
+ConnectServerInfo  	CONNECT_SERVER_INFO		3	NEGATIVE
 InterruptAttach  	INTERRUPT_ATTACH  		5	NEGATIVE
-InterruptDetachFunc INTERRUPT_DETACH_FUNC 	2	NORMAL
+InterruptDetachFunc INTERRUPT_DETACH_FUNC 		2	NORMAL
 InterruptDetach  	INTERRUPT_DETACH 		1	NORMAL
 InterruptWait  		INTERRUPT_WAIT  		2	NORMAL
 MsgCurrent  		MSG_CURRENT  			1	NORMAL
 MsgDeliverEvent  	MSG_DELIVER_EVENT  		2	NORMAL
 MsgVerifyEvent  	MSG_VERIFY_EVENT  		2	NORMAL
-MsgError  			MSG_ERROR  				2	NORMAL
-MsgInfo  			MSG_INFO  				2	NORMAL
+MsgError  			MSG_ERROR		2	NORMAL
+MsgInfo  			MSG_INFO		2	NORMAL
 MsgKeyData  		MSG_KEYDATA  			6	NORMAL
 MsgRead  			MSG_READV  				4	NEGATIVE 3
 MsgReadiov  		MSG_READIOV  			5	NEGATIVE
@@ -193,16 +189,16 @@ SyncSemPost  		SYNC_SEM_POST  			1	NORMAL
 SyncSemWait  		SYNC_SEM_WAIT  			2	NORMAL
 ThreadCancel  		THREAD_CANCEL  			2	NORMAL
 ThreadCreate  		THREAD_CREATE  			4	NEGATIVE
-ThreadCtl  			THREAD_CTL  			2	NORMAL
+ThreadCtl			THREAD_CTL			2	NORMAL
 ThreadDestroy  		THREAD_DESTROY  		3	NORMAL
 ThreadDetach  		THREAD_DETACH  			1	NORMAL
 ThreadJoin  		THREAD_JOIN  			2	NORMAL
 TimerAlarm  		TIMER_ALARM  			3	NORMAL
 TimerCreate  		TIMER_CREATE  			2	NEGATIVE
 TimerDestroy  		TIMER_DESTROY  			1	NORMAL
-TimerInfo 		 	TIMER_INFO 		 		4	NEGATIVE
+TimerInfo		TIMER_INFO			4	NEGATIVE
 TimerSettime  		TIMER_SETTIME  			4	NORMAL
 TimerTimeout  		TIMER_TIMEOUT  			5	NEGATIVE
-MtCtl				MT_CTL					2	NORMAL
+MtCtl			MT_CTL				2	NORMAL
 
 HERE
